### ISSUE TITLE
Should not happen: received removal of unseen element

### ISSUE THREAD

**Issue by skeggse** [StreakYC/page-parser-tree#3]
I'm seeing the following exception, but I haven't managed the root cause yet. Where should I be focusing my attention?

```
Error: Should not happen: received removal of unseen element
  at ? (node_modules/page-parser-tree/js/index.js:221:49)
  at Array.forEach(<anonymous>)
  at changesToDeliver(node_modules/page-parser-tree/js/index.js:207:39)
  at ? (node_modules/live-set/index.js:81:21)
  at Array.forEach(<anonymous>)
  at ? (node_modules/live-set/index.js:72:35)
  at ? (node_modules/live-set/Scheduler.js:40:22)
  at value(node_modules/live-set/Scheduler.js:63:16)
  at onerror(node_modules/live-set/Scheduler.js:53:5)
  at call(node_modules/asap/browser-asap.js:54:18)
  at MutationObserver.k(node_modules/asap/browser-raw.js:52:29)
```

**Comment by AgentME** [comment]
Did you get any other errors in the same session? The situation that causes the "watcher received element twice" error can lead to the error here. If that's the case for you, and you find that it's not possible or convenient to make exclusive watchers that can't find the same elements, then I can try to make that situation better handled.

If you aren't getting any other errors: can you tell me what the value of the variable `changes` looks like at the time the error is thrown? (A conditional breakpoint of `!node` on the `if (!node) throw new Error('Should not happen...');` line should be useful. If the browser has optimized out access to `changes` at that point in the `changes.forEach` callback, then step up a stack frame or two in the debugger and try to access `changes` again.) I'm curious whether there might be multiple add and remove events in the changes array at that time for the same element; I don't know of any problems in that situation though.

Can you give a description of the watcher configuration for that tag and its sources' watchers?

**Comment by skeggse** [comment]
Ahh, I _did_ see "watcher received element twice" errors. That makes sense, and I'll dig into that. Thanks!
